project:
  type: website
  render:
    - index.qmd
    - tensorflow/guide/*.qmd
    - keras/guides/*.qmd
  preview:
    port: 5555
    browser: false


toc: true



format:
  html:
    code-copy: true

execute:
  freeze: true




website:
  title: "tf-site-title"

