project:
  type: website
  execute-dir: project
  render:
    - index.qmd
    - tensorflow/guide/*.qmd
    - keras/guides/*.qmd
  preview:
    port: 5555
    browser: false

execute:
  freeze: auto

website:
  title: TensorFlow for R
  site-url: https://tensorflow.rstudio.com
  repo-url: https://github.com/t-kalinowski/tf-site
  page-navigation: true
  reader-mode: true
  favicon: "images/favicon/icon.png"
  navbar:
    search: true
    logo: "images/favicon/icon.png"
  sidebar:
    - title: TensorFlow
      search: true
      contents:
        - text: Tensorflow Basics
        - text: Overview
          href: tensorflow/guide/basics.qmd
        - text: Tensors
          href: tensorflow/guide/tensor.qmd
        - text: Variables
          href: tensorflow/guide/variable.qmd
        - text: Automatic differentiation
          href: tensorflow/guide/autodiff.qmd
        - text: Graphs and functions
          href: tensorflow/guide/intro_to_graphs.qmd


format:
  html:
    toc: true
    code-overflow: wrap
    theme: united
