project:
  type: website
  output-dir: _site
  render:
    - "**.qmd"
    - "!v1/**"
    - "examples/**"
    - "!examples/_check/**"
    - "reference/**/**.md"

  # pre-render: spin-examples.R
  preview:
    port: 5555
    browser: false

execute:
  enabled: true
  eval: true
  freeze: auto

website:
  title: TensorFlow for R
  site-url: https://t-kalinowski.github.io/tensorflow.rstudio.com/
  repo-url: https://github.com/t-kalinowski/tensorflow.rstudio.com
  # Uncomment when we move to tensorflow.rstudio.com
  # google-analytics: "UA-20375833-3"
  repo-actions: [edit, source, issue]
  search: true
  page-navigation: true
  reader-mode: true
  favicon: "images/favicon/icon.png"
  page-footer:
    left: |
      Proudly supported by
      [![](https://www.rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-flat.svg){fig-alt="RStudio" width=65px}](https://www.rstudio.com)
    right:
      - icon: github
        href: https://github.com/rstudio/tensorflow
        aria-label: GitHub repository
  navbar:
    search: true
    logo: "images/favicon/icon.png"
    file: index.qmd
    left:
      - { text: Install, href: install/ }
      - { text: Tutorials, href: tutorials/ }
      - { text: Guides, href: guides/ }
      - { text: Examples, href: examples/ }
      - { text: Reference, href: reference/ }

  sidebar:
    - title: "Install"
      alignment: left
      collapse-level: 2
      style: "docked"
      contents:
        - install/index.qmd
        - install/custom.qmd
        - section: GPU
          href: install/gpu/index.qmd
          contents:
            - install/gpu/local_gpu/index.qmd
            - install/gpu/cloud_server_gpu/index.qmd

    - title: "Tutorials"
      contents:
        - tutorials/index.qmd
        - section: Quickstart
          contents:
            - tutorials/quickstart/beginner.qmd
            - tutorials/quickstart/advanced.qmd
        - section: "ML basics with Keras"
          contents:
            - tutorials/keras/classification.qmd
            - tutorials/keras/text_classification.qmd
            - tutorials/keras/text_classification_with_hub.qmd
            - tutorials/keras/regression.qmd
            - tutorials/keras/overfit_and_underfit.qmd
            # - tutorials/keras/save_and_load.qmd



    - title: "Reference"
      contents:
        - reference/index.qmd
        - text: Packages
        - text: -----
        - { section: "tensorflow", href: "reference/tensorflow/index.qmd" }
        - { text: "keras", href: "reference/keras/index.qmd" }
        - { text: "tfdatasets", href: "reference/tfdatasets/index.qmd" }
        - { text: "tfautograph", href: "reference/tfautograph/index.qmd" }
        - { text: "tfhub", href: "reference/tfhub/index.qmd" }
        - { text: "tfruns", href: "reference/tfruns/index.qmd" }


    - title: "Guides"
      contents:
        - guides/index.qmd

        - section: Tensorflow Basics
          contents:
            - { text: Overview, href: guides/tensorflow/basics.qmd }
            - { text: Tensors, href: guides/tensorflow/tensor.qmd }
            - { text: Variables, href: guides/tensorflow/variable.qmd }
            - { text: Automatic differentiation, href: guides/tensorflow/autodiff.qmd }
            - { text: Graphs and functions, href: guides/tensorflow/intro_to_graphs.qmd }

        - section: Keras
          contents:
            - guides/keras/sequential_model.qmd
            - guides/keras/functional_api.qmd
            - guides/keras/training_with_built_in_methods.qmd
            - guides/keras/making_new_layers_and_models_via_subclassing.qmd
            - guides/keras/serialization_and_saving.qmd
            - guides/keras/preprocessing_layers.qmd
            - guides/keras/customizing_what_happens_in_fit.qmd
            - guides/keras/writing_a_training_loop_from_scratch.qmd
            - guides/keras/working_with_rnns.qmd
            - guides/keras/understanding_masking_and_padding.qmd
            - guides/keras/writing_your_own_callbacks.qmd
            - guides/keras/transfer_learning.qmd

        - section: TensorFlow in depth
          contents:
            - guides/tensorflow/tensor_slicing.qmd
            - { text: Autograph, href: guides/tfautograph/index.qmd }

        - section: Data input pipelines
          contents:
            - guides/tfdatasets/index.qmd

        - section: Track Experiments
          contents:
            - guides/tfruns/index.qmd
            - guides/tfruns/managing.qmd
            - guides/tfruns/tuning.qmd
            - guides/tensorboard/index.qmd

        - section: Deployment
          href: guides/deploy/index.qmd
          contents:
            - guides/deploy/plumber.qmd
            - guides/deploy/shiny.qmd
            - guides/deploy/docker.qmd

format:
  html:
    toc: true
    code-overflow: wrap
    mainfont: Lato
    theme:
      light: [flatly, light.scss, custom.scss]
      dark: [darkly, dark.scss, custom.scss]
