[[redirects]]
  from = "http://keras.rstudio.com/*"
  to = "http://tensorflow.rstudio.com/:splat"
  force = true

[[redirects]]
  from = "https://keras.rstudio.com/*"
  to = "https://tensorflow.rstudio.com/:splat"
  force = true


# If skip_processing = true, all other settings are ignored
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = false
