project:
  type: website
  output-dir: ../_site
  render:
    - "**.qmd"
    # - "!examples"
  preview:
    port: 5555
    browser: true

execute:
  enabled: false
  eval: false
  freeze: auto


website:
  title: TensorFlow for R
  site-url: https://tensorflow.rstudio.com
  repo-url: https://github.com/t-kalinowski/tf-site
  repo-actions: [edit, source, issue]
  search: true
  page-navigation: true
  reader-mode: true
  favicon: "images/favicon/icon.png"
  navbar:
    search: true
    logo: "images/favicon/icon.png"
    file: index.qmd
    left:
      - {text: Install      ,href: install/}
      - {text: Tutorials    ,href: tutorials/}
      - {text: Guides       ,href: guides/}
      - {text: Examples     ,href: examples/}
      - {text: Reference    ,href: reference/}
      - {text: v1           ,href: v1/}



  sidebar:
    metadata-file: guides/sidebar.yml
    contains:
    - title: "Install"
      search: true
      collapse-level: 2
      style: docked
      contents:
        - install/
        - install/gpu/

    - title: "Tutorials"
      contents:
        - tutorials/

    - title: "Guides"

      id: guides
      contents:
        - index.qmd
        - section: Tensorflow Basics
          contents:
            - {text: Overview                  ,href: guides/tensorflow/basics.qmd}
            - {text: Tensors                   ,href: guides/tensorflow/tensor.qmd}
            - {text: Variables                 ,href: guides/tensorflow/variable.qmd}
            - {text: Automatic differentiation ,href: guides/tensorflow/autodiff.qmd}
            - {text: Graphs and functions      ,href: guides/tensorflow/intro_to_graphs.qmd}
        - section: "---"
        - section: Keras
          contents:
            - guides/keras/sequential_model.qmd
            - guides/keras/functional_api.qmd
            - guides/keras/making_new_layers_and_models_via_subclassing.qmd
            - guides/keras/customizing_what_happens_in_fit.qmd
            - guides/keras/preprocessing_layers.qmd
            - guides/keras/transfer_learning.qmd
            - guides/keras/working_with_rnns.qmd
            - guides/keras/writing_your_own_callbacks.qmd
        - section: Advanced
          contents:
            - guides/keras/python_subclasses.qmd

    - title: "Reference"
      search: true
      contents:
        - reference/index.qmd


# metadata-files:
#   - guides/_metadata.yml

format:
  html:
    toc: true
    code-overflow: wrap
    theme:
      light: united
      dark: darkly
